version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    pre_build:
      - sphinx-apidoc -f -e -o ./api/ ../src/trusspy/

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .